{% set name = "ipyaladin" %}
{% set version = "0.1.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyaladin-{{ version }}.tar.gz
  sha256: 1c4be1b939ee335864cd26a0dd1d177823a83ff80543ccc100d941050b84f1ae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipywidgets >=6.0.0
    - python >=3.6

test:
  imports:
    - ipyaladin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cds-astro/ipyaladin
  summary: ipyaladin
  license: BSD-3-Clause
  license_file: ipyaladin-LICENSE-BSD-3

extra:
  recipe-maintainers:
    - tboch
