{% set name = "ipyaladin" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyaladin-{{ version }}.tar.gz
  sha256: 8e10e2b9e9486a0d1ef45cc63d776714e911bd442624ceb5106dc06d7277246c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - jupyter-packaging
    - jupyterlab
  run:
    - python >=3.7
    - jupyterlab
    - jupyter
    - ipywidgets >=7.6.0,<9

test:
  imports:
    - ipyaladin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cds-astro/ipyaladin
  license: BSD-3-Clause
  license_file: ipyaladin-LICENSE-BSD-3
  summary: ipyaladin
  description: ipyaladin, a Jupyter widget for Aladin Lite
  doc_url: https://aladin.u-strasbg.fr/AladinLite/doc/API/
  dev_url: https://github.com/cds-astro/ipyaladin

extra:
  recipe-maintainers:
    - bmatthieu3
    - tboch
