{% set name = "ipyaladin" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyaladin-{{ version }}.tar.gz
  sha256: a7a1f0a0ae176dd9faa0e05e7ccd12b0722bb329616fdebbbd42bb6ea8498e41

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation


requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-jupyter-builder >=0.5.0
    - pip
  run:
    - python >=3.8
    - anywidget
    - jupyterlab

test:
  imports:
    - ipyaladin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cds-astro/ipyaladin
  license: BSD-3-Clause
  license_file: ipyaladin-LICENSE-BSD-3
  summary: ipyaladin
  description: ipyaladin, a Jupyter widget for Aladin Lite, the sky viewer
  doc_url: https://aladin.u-strasbg.fr/AladinLite/doc/API/
  dev_url: https://github.com/cds-astro/ipyaladin

extra:
  recipe-maintainers:
    - bmatthieu3
    - tboch
